### ISSUE TITLE
To many files open error

### ISSUE THREAD

**Issue by yoanhg421** [avalonv/reCBZ#25]
I;m getting this error, on mac. i tried diffrent size archives. same error, 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/recbz", line 8, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/reCBZ/__main__.py", line 392, in main
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 728, in rmtree
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 725, in rmtree
OSError: [Errno 24] Too many open files: '/var/folders/bd/trf4b_ld6xz0xg2nq_00g51r0000gn/T/reCBZCACHE_f82012de722e44459cbd9ec343aef307'

**Comment by BelardoA** [comment]
I fixed this in my version of the application here: https://github.com/BelardoA/reCBZ2

**Comment by yoanhg421** [comment]
Thank you.  I’ll check it out soon.
